name: CI/CD Pipeline - Auto Merge to Staging

on:
  push:
    branches-ignore:
      - staging
      - master

permissions:
  contents: write

jobs:
  run-tests-and-merge:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout branch
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt

      - name: Run tests
        run: |
          source venv/bin/activate
          pytest --maxfail=1 --disable-warnings -v

      - name: Merge branch into staging
        if: success()
        uses: devmasx/merge-branch@v1.4.0
        with:
          type: now
          from_branch: ${{ github.ref_name }}
          target_branch: staging
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_GITHUB_TOKEN }}
